// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: user/messenger.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Messenger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Messenger) Reset() {
	*x = Messenger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_messenger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Messenger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Messenger) ProtoMessage() {}

func (x *Messenger) ProtoReflect() protoreflect.Message {
	mi := &file_user_messenger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Messenger.ProtoReflect.Descriptor instead.
func (*Messenger) Descriptor() ([]byte, []int) {
	return file_user_messenger_proto_rawDescGZIP(), []int{0}
}

func (x *Messenger) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Messenger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Messenger) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AddMessengerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    int64      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Messenger *Messenger `protobuf:"bytes,2,opt,name=messenger,proto3" json:"messenger,omitempty"`
	Error     string     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddMessengerResponse) Reset() {
	*x = AddMessengerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_messenger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMessengerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMessengerResponse) ProtoMessage() {}

func (x *AddMessengerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_messenger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMessengerResponse.ProtoReflect.Descriptor instead.
func (*AddMessengerResponse) Descriptor() ([]byte, []int) {
	return file_user_messenger_proto_rawDescGZIP(), []int{1}
}

func (x *AddMessengerResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddMessengerResponse) GetMessenger() *Messenger {
	if x != nil {
		return x.Messenger
	}
	return nil
}

func (x *AddMessengerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddMessengerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messenger *Messenger `protobuf:"bytes,1,opt,name=messenger,proto3" json:"messenger,omitempty"`
	UserId    uint32     `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *AddMessengerRequest) Reset() {
	*x = AddMessengerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_messenger_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMessengerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMessengerRequest) ProtoMessage() {}

func (x *AddMessengerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_messenger_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMessengerRequest.ProtoReflect.Descriptor instead.
func (*AddMessengerRequest) Descriptor() ([]byte, []int) {
	return file_user_messenger_proto_rawDescGZIP(), []int{2}
}

func (x *AddMessengerRequest) GetMessenger() *Messenger {
	if x != nil {
		return x.Messenger
	}
	return nil
}

func (x *AddMessengerRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RemoveMessengerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessengerId uint32 `protobuf:"varint,1,opt,name=messenger_id,json=messengerId,proto3" json:"messenger_id,omitempty"`
	UserId      uint32 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *RemoveMessengerRequest) Reset() {
	*x = RemoveMessengerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_messenger_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMessengerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMessengerRequest) ProtoMessage() {}

func (x *RemoveMessengerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_messenger_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMessengerRequest.ProtoReflect.Descriptor instead.
func (*RemoveMessengerRequest) Descriptor() ([]byte, []int) {
	return file_user_messenger_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveMessengerRequest) GetMessengerId() uint32 {
	if x != nil {
		return x.MessengerId
	}
	return 0
}

func (x *RemoveMessengerRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RemoveMessengerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RemoveMessengerResponse) Reset() {
	*x = RemoveMessengerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_messenger_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMessengerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMessengerResponse) ProtoMessage() {}

func (x *RemoveMessengerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_messenger_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMessengerResponse.ProtoReflect.Descriptor instead.
func (*RemoveMessengerResponse) Descriptor() ([]byte, []int) {
	return file_user_messenger_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveMessengerResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RemoveMessengerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_user_messenger_proto protoreflect.FileDescriptor

var file_user_messenger_proto_rawDesc = []byte{
	0x0a, 0x14, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x65, 0x6e,
	0x67, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x6e, 0x0a,
	0x14, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28, 0x0a,
	0x09, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x09, 0x6d, 0x65,
	0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x58, 0x0a,
	0x13, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x65, 0x6e,
	0x67, 0x65, 0x72, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x54, 0x0a, 0x16, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x47, 0x0a,
	0x17, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_messenger_proto_rawDescOnce sync.Once
	file_user_messenger_proto_rawDescData = file_user_messenger_proto_rawDesc
)

func file_user_messenger_proto_rawDescGZIP() []byte {
	file_user_messenger_proto_rawDescOnce.Do(func() {
		file_user_messenger_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_messenger_proto_rawDescData)
	})
	return file_user_messenger_proto_rawDescData
}

var file_user_messenger_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_messenger_proto_goTypes = []interface{}{
	(*Messenger)(nil),               // 0: Messenger
	(*AddMessengerResponse)(nil),    // 1: AddMessengerResponse
	(*AddMessengerRequest)(nil),     // 2: AddMessengerRequest
	(*RemoveMessengerRequest)(nil),  // 3: RemoveMessengerRequest
	(*RemoveMessengerResponse)(nil), // 4: RemoveMessengerResponse
}
var file_user_messenger_proto_depIdxs = []int32{
	0, // 0: AddMessengerResponse.messenger:type_name -> Messenger
	0, // 1: AddMessengerRequest.messenger:type_name -> Messenger
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_messenger_proto_init() }
func file_user_messenger_proto_init() {
	if File_user_messenger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_messenger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Messenger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_messenger_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMessengerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_messenger_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMessengerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_messenger_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveMessengerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_messenger_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveMessengerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_messenger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_messenger_proto_goTypes,
		DependencyIndexes: file_user_messenger_proto_depIdxs,
		MessageInfos:      file_user_messenger_proto_msgTypes,
	}.Build()
	File_user_messenger_proto = out.File
	file_user_messenger_proto_rawDesc = nil
	file_user_messenger_proto_goTypes = nil
	file_user_messenger_proto_depIdxs = nil
}
